sudo: required
language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby

before_script:
  - sh -e /etc/init.d/xvfb start
  - |
      if [[ $BROWSER == *"chrome"* ]]; then
        sudo apt-get -y purge chromium-browser
        export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
        curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
        unzip chrome-linux.zip
        sudo ln -sf $PWD/chrome-linux/chrome-wrapper /usr/local/bin/chrome
        export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
      fi
  - |
      if [[ $BROWSER == *"firefox"* ]]; then
        export GECKODRIVER_VERSION=v0.11.1
        curl -L -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        gunzip -c geckodriver.tar.gz | tar xopf -
        chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
        pip install --user mozdownload mozinstall
        mozdownload --version latest --destination firefox.tar.bz2
        mozinstall firefox.tar.bz2
        sudo ln -sf $PWD/firefox/firefox /usr/local/bin/firefox
        firefox --version
      fi

script: bundle exec rake $RAKE_TASK

env:
  - RAKE_TASK=spec
  - RAKE_TASK=features:watir_webdriver BROWSER=local_chrome
  - RAKE_TASK=features:selenium_webdriver BROWSER=local_chrome
  - RAKE_TASK=features:watir_webdriver BROWSER=local_firefox
  - RAKE_TASK=features:selenium_webdriver BROWSER=local_firefox
