sudo: false
rvm:
  - 2.2.5
addons:
  firefox: latest
  apt:
    packages:
      - unzip
      - libxss1
cache: bundler
before_script:
  - support/travis.sh
  - export PATH=$PWD/chrome-linux:$PATH
script: bundle exec rake features:watir_webdriver
