sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
addons:
  firefox: latest
before_script:
  - sh -e /etc/init.d/xvfb start
  - mkdir travis-drivers
  - export PATH=$PWD/travis-drivers:$PATH
  - |
      CHROME_REVISION=417841
      curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
      unzip chrome-linux.zip

      CHROMEDRIVER_VERSION=$(curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      mv chromedriver travis-drivers/chromedriver
      chmod +x travis-drivers/chromedriver
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=features:watir_webdriver
