sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
addons:
  firefox: latest
before_script:
  - sh -e /etc/init.d/xvfb start
  - mkdir travis-drivers
  - export PATH=$PWD/travis-drivers:$PATH
  - |
      if [[ $BROWSER == *"chrome"* ]]; then
        CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
        curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
        unzip chrome-linux.zip

        CHROMEDRIVER_VERSION=$(curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        mv chromedriver travis-drivers/chromedriver
      fi
  - |
      if [[ $BROWSER == *"firefox"* ]]; then
        export GECKODRIVER_VERSION=v0.11.1
        curl -L -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        gunzip -c geckodriver.tar.gz | tar xopf -
        chmod +x geckodriver

        mv geckodriver travis-drivers/geckodriver
        geckodriver --version
        firefox --version
      fi
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=features:watir_webdriver BROWSER=local_chrome
