sudo: false
rvm:
  - 2.2.5
addons:
  firefox: latest
  apt:
    packages:
      - unzip
      - libxss1
cache: bundler
before_script:
  - mkdir travis-drivers
  - export PATH=$PWD/travis-drivers:$PATH
  - support/travis.sh
script: bundle exec rake features:watir_webdriver
